### ISSUE TITLE
The constant ContextKey in class ContextManager can not be "const"

### ISSUE THREAD

**Issue by rcjuliano** [thiagolunardi/MvcMusicStoreDDD#10]
Hi Thiago,

In the "Context Manager" class, the attribute "Context Key" is setted as constant. However, in the constructor method, its value tries to be changed.

```
   private const string ContextKey = "ContextManager.Context";

    public ContextManager()
    {
        ContextKey = "ContextKey." + typeof(TContext).Name;
    }
```

**Comment by thiagolunardi** [comment]
Damm... your're right. 
I am finishing a new pull that will correct this.
Tks man!
