### ISSUE TITLE
DDD inconsistencies

### ISSUE THREAD

**Issue by petrfleischmann** [thiagolunardi/MvcMusicStoreDDD#12]
Hi,
I learn DDD and I don't undestand why:
1) The project layout is not using domain, but is used "interfaces, services layout":
 Domain/Services/A, Domain/Entities/A vs Domain/A/serviceA.cs, entityA.cs
I thing Domain/A/serviceA.cs, entityA.cs is cleaner.

2) Why is domain amnemic (all data access is via services)
3) Why a data minig methods are in application services and not in domain or domain services.

**Comment by thiagolunardi** [comment]
1) It is, really, an amnemic domain, but still domain driven developed
2) "These are currently an early work in progress.", and others collaborator already forked the project and they should start doing pull request this quarter to comply this.
3) The same reason of item 2. And it is a very simple project, probably no DDD was required. If you have a better approuch, you are more than welcome to submit pull request and improove this "template" even more.
