### ISSUE TITLE
ContextManager e HttpContext

### ISSUE THREAD

**Issue by awquadros** [thiagolunardi/MvcMusicStoreDDD#13]
Quando Eric Evans fala sobre Arquitetura em camadas, ele deixa claro que um principio essencial é que cada elemento de uma camada dependa somente de outros elementos na mesma camada, ou de uma camada inferior.

Quando você utiliza a Classe HttpContext na sua Classe ContextManager você está violando essa regra. Em outras palavras, sua camada de persistência não deve ter conhecimento algum sobre camadas acima dela. Nem sempre HttpContext estará disponível.

Talvez a Classe ContextManager nem deva existir, se ela não tiver um objetivo maior do que o atual.

**Comment by jedielson** [comment]
Foi discutido sobre isso nessa [Issue](https://github.com/thiagolunardi/MvcMusicStoreDDD/issues/9)

0/

**Comment by thiagolunardi** [comment]
@awquadros, A cama de CrossCutting, inevitavelmente, depende de outras camadas. A biblioteca de dados depende da de Domain para implementar suas interface, a de IoC depende de quase tudo para poder fazer suas injeções, e assim por diante.

E sem a ContextManager, como vc vai garantir que haverá apenas um contexto por request?

**Comment by awquadros** [comment]
@jedielson li a issue que você citou, eu não tinha visto ela antes.

@thiagolunardi quem sabe adicionar algum tipo de configuração para a camada de acesso a dados, possibilitando a escolha de uma estratégia para o funcionamento do ContextManager, assim poderíamos implementar e escolher como o ContextManager vai manter essa única instância. Teríamos uma estratégia para OWIN, WPF, Web, etc ...

É uma ideia.

**Comment by thiagolunardi** [comment]
@awquadros , o ContextManager é dedicado. Esse é para atender um appWeb e atender um pattern de OneContextPerRequest. Sem me orientar pelo HttpContext, não teria jeito.

E não é intenção atender outras necessidades, como WPF, WinForms ou CommandPrompt.
