### ISSUE TITLE
Dúvida Entidade

### ISSUE THREAD

**Issue by miltomcamara** [thiagolunardi/MvcMusicStoreDDD#15]
Olá Thiago, tudo bem? Gostei muito do modelo do seu projeto e estou estudando para entender melhor o conceito do DDD junto com o livro do Eric Evans.

Me surgiu uma dúvida em relação às Entidades, notei que você coloca na classe uma propriedade IsValid, correto? Porem essa propriedade faz a consistência dos dados como um todo! E se eu quisesse inserir um campo extra (update), como eu validaria somente essa informação?

Ex.: A entidade produto tem os campos nome e preço como obrigatório que teria que ser válidado no IsValid, e se existisse um campo que aceitasse null e eu quisesse inserir essa informação posteriormente, compreende, como eu faria a validação desse campo isoladamente!?

Muito obrigado!

Milton

**Comment by thiagolunardi** [comment]
Olá Milton!

O `IsValid` testa a entidade como um todo. Pois toda entidade deve ser capaz de se auto validar.

Para validação de atualização como quer fazer, de uma olhada no meu outro repositório, o [auctionhouse](https://github.com/thiagolunardi/auctionhouse). Nele existem [exemplos de validação para updates](https://github.com/thiagolunardi/auctionhouse/blob/master/src/Auctionata.Domain/Entities/Item.cs) melhores definidos. Acredito que seja exatamente o que está procurando.
