### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by miltomcamara** [thiagolunardi/MvcMusicStoreDDD#18]
Olá Thiago, tudo bem?

Analisando o seu código, verifiquei que você utiliza as validações somente no método IsValid(). 

Vamos supor que eu queira lançar notificações baseado em alguma condição, posso utilizar o mesmo modelo que você faz para validar uma Entity ou esse modelo é somente para validação?

Muito obrigado

Milton

**Comment by thiagolunardi** [comment]
De uma olhanda neste meu outro [repositório](https://github.com/thiagolunardi/auctionhouse). Nele eu uso as validação para fazer exatamente o que voce que. Veja nessa [entidade de dominio](https://github.com/thiagolunardi/auctionhouse/blob/master/src/Auctionata.Domain/Entities/Room.cs) os métodos `TryDoSomenthing()`.
