### ISSUE TITLE
Dependencia System.Web no projeto Data

### ISSUE THREAD

**Issue by miltoncamara** [thiagolunardi/MvcMusicStoreDDD#19]
E aí Thiago, tudo bem?

A respeito da dependência System.Web no projeto Data, será que temos outra alternativa para trabalharmos com o Gerenciamento do Contexto? Estou utilizando dessa forma que você fez e funciona perfeitamente, porém não soa muito bem essa DLL.

Muito obrigado! :)

**Comment by EduardoPires** [comment]
Olá @miltoncamara  Recomendo abandonar esta abordagem e usar o próprio injetor (no caso SimpleInjector) para fazer a resolução. Tenho exemplos no meu GitHub.

**Comment by miltoncamara** [comment]
Opaaa, valeu @EduardoPires, qual projeto você aborda esse tema? Vou fazer um fork para estudar um pouco mais a fundo!

**Comment by EduardoPires** [comment]
Neste aqui você tem um exemplo clássico e que funciona muito bem (não precisa isolar o Identity se quiser)
https://github.com/EduardoPires/IdentityIsolation

Em ASP.NET Core:
https://github.com/EduardoPires/EquinoxProject
