### ISSUE TITLE
Por que IRepository precisa implementar IDisposable?

### ISSUE THREAD

**Issue by BrunoMazzo** [thiagolunardi/MvcMusicStoreDDD#2]
Não existe nenhuma implementação de IRepository que não seja IDisposable? 

No meu ponto de vista IDisposable é um vazamento de lógica. Você está favorecendo implementações que utilizem banco de dados ou coisas do tipo, assim faria sentido o IDisposable, mas dai eu teria que discordar do nome (seria melhor IDatabaseRepository ou algo do tipo). Não acha melhor apenas marcar as classes com IDisposable e deixar a interface sem essa responsabilidade?

Gostaria de ouvir sua opinião sobre o assunto.

**Comment by thiagolunardi** [comment]
Olá Bruno!

Acho que não entendi bem sua dúvida. Eu parto do princípio que um repositório, de uma forma ou outra, é um local de persistência de dados, seja banco de dados, serial, etc.

Eu acredito que exigir IDisposable de uma interface dedicada a repositórios apenas reduz a chance de se "largar" algum contexto ainda conectado, ou de esquecer se é necessário ser explícito na liberação de algum recurso.

**Comment by thiagolunardi** [comment]
Posso fechar o chamado, @BrunoMazzo ?

**Comment by BrunoMazzo** [comment]
Eu concordo que não faz muito mal colocar o IDisposable, mas acho isso um code smell. Por exemplo, digamos que eu implemente um repositório de teste que irá apenas deixar dados em cache na memória. Ele é uma implementação válida da interface, em alguns casos isso pode resolver temporariamente muitos problemas, em outros pode ser a solução final, entretanto teria que obrigatoriamente implementar o IDisposable sem necessidade porque a interface me obriga. 

O que eu quero dizer é que o IDisposable é contra o Interface segregation principle do SOLID, porque você está atribuindo mais de uma responsabilidade para a interface. Ela tem a responsabilidade de recuperar dados e também de limpar qualquer recurso. No meu ponto de vista a responsabilidade de limpar os recursos não é da interface, mas sim do objeto que implementar ela, se ele precisar limpar.

Essa é mais uma questão de opinião. Se você acha diferente, sem problemas.

**Comment by thiagolunardi** [comment]
Legal, Bruno!
Me vendeu pela responsabilidade e pelo ISP.
Vou subir um update com Fix para essa thread.
Obrigado pela participação.
