### ISSUE TITLE
Porque StoreManagerController chama Dispose nas suas dependências?

### ISSUE THREAD

**Issue by BrunoMazzo** [thiagolunardi/MvcMusicStoreDDD#3]
O controller StoreManagerController  recebe três dependências. Ele não deveria controlar o tempo de vida delas se não me engano. Quando usamos injeção de dependência é função do IOC criar, montar e destruir os objetos. Os objetos que recebem as dependências então não se preocupam em destruir ou liberar nenhum dos recursos porque não sabem se esses recursos são compartilhados com outros objetos.

Por exemplo: se um dos serviços pode ser compartilhado entre controllers? Ao realizar o Dispose os outros controllers que utilizam o mesmo objeto vão passar a dar erro.

Novamente, aguardo sua opinião sobre o assunto.

**Comment by thiagolunardi** [comment]
Bruno,
Não é bem assim que o IoC funciona.

Não vejo um serviço sendo compartilhado entre controllers, mas confesso que não sei bem por onde começar minha defesa sem deixar a resposta com 3 páginas de texto.

Vou pedir ajuda para o @EduardoPires nessa ok?

@EduardoPires , pode ajudar na orientação do @BrunoMazzo , por gentileza?

**Comment by BrunoMazzo** [comment]
Estou usando como base o Livro: [Dependency Injection NET](http://www.amazon.com/Dependency-Injection-NET-Mark-Seemann/dp/1935182501)

Segundo ele, um IoC tem três funções:
* Criar objetos e suas dependências
* Gerenciar o ciclo de vida desses objetos
* Realizar interceptação de chamadas

No caso de você chamar Disposable, você estaria quebrando o segundo item, porque você que diz quando o objeto deixa de existir, não o IoC
