### ISSUE TITLE
Opinião sobre o self validation

### ISSUE THREAD

**Issue by landrade** [thiagolunardi/MvcMusicStoreDDD#4]
Acredito que esse tipo de "comportamento" não seja necessário, pois no meu ponto de vista, um objeto só pode existir se ele for valido. Logo no lugar de você estar perguntando se aquela instancia é valida, você já sabe que se existir uma instancia o objeto é valido.

Um exemplo: 
Considerando uma pessoa, ela não pode ter a data de nascimento dela no futuro.... logo ela é "invalida" e não existe. Podemos transferir esse comportamento para o OO no construtor da class Pessoa caso a data seja invalida, não iremos criar uma instancia.

O que você acha dessa abordagem?

**Comment by thiagolunardi** [comment]
Andrade, acho muito bacana. 
Realmente você passa a validar um objeto logo na sua criação.

O que foi implementado aí foi o princípio de Especificação (por Martin Fowler), onde atende:
* Um domínio/entidade deve ser capaz de se auto validar;
* Um serviço de domínio deve ser capaz de validar o estado das entidades contra suas especificações

O que muda é o momento da validação (no caso que fiz foi antes da persistência), e também a possibilidade de criar mais especificações, expandindo esse recurso. Por exemplo: Validar se um personagem do sistema está apto para realizar uma ação, como um documento se está apto a ser aprovado, se um registro realmente pode ser excluído, se um produto está mesmo em estoque, etc.

Você cria várias classes de especificação de acordo com o que foi documentado pelo cliente/PO/analista de negócio. E cria um validador para testar todas as especificações retornando se o personagem/object está ou não apto a realização uma ação de acordo com que foi especificado.

Então, implementar Specifications não está limitada apenas no contexto de validar uma entidade, e sim de validar em qualquer momento onde existam condições para tornar esse objeto apto a realizar/sofre uma ação.

Olhando nos conceitos do Vernon, ele sempre faz os testes logo no início dos métodos (uns Asserts). Em alguns métodos possuem vários testes (Asserts) na entrada do método. O que o Specification faz é organizar esse trecho, isolando as especificações e criando validadores (agrupadores de especificações) que são chamados de uma única vez. E ao invés de retornarem uma exception, retornam um ValidationResult, com uma propriedade informando se está ou não válido, e se não tiver, uma coleção de mensagens de erro da validação.

Eu, pessoalmente, não gosto do uso literal dos Asserts, pois ele retorna Exception. Então, se em um formulário, por exemplo, um campo estiver errado e este possuir 3 validações, eu terei que fazer 3 submits + 1 do formulário até passar com sucesso. Usando Specifications, no primeiro submit já irá retornar 3 mensagens dizendo quais especificações não passaram.

Como vc faz hoje?

Fonte:
http://www.martinfowler.com/apsupp/spec.pdf

**Comment by thiagolunardi** [comment]
Posso fechar o chamado, @landrade ?

**Comment by landrade** [comment]
@thiagolunardi estou sem tempo para responder com calma.... Pode fechar que assim que eu tiver um tempo legal para responder com calma, eu posto aqui de marcando!
