### ISSUE TITLE
Qual o IoC usar no projeto mas usado ou mais rápido?

### ISSUE THREAD

**Issue by alvpaz** [thiagolunardi/MvcMusicStoreDDD#5]
Gostaria de verificar com pessoal qual opinião de qual usar 

StructureMap
Castelo de Windsor
Ninject
Autofac
Unidade
Spring.NET
Link comparando cada um: 
http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison

No projeto que participei usamos o Ninject, mas dizem que é muito lento.

**Comment by thiagolunardi** [comment]
Ninject para projetos simples e/ou didáticos.
SimpleInjector para performance.

Recentemente fiz uma substituição em um projeto de um cliente do Ninject pelo SimpleInjector. O ganho foi de 90%. A WebAPI passou a responder 10x mais rápido.

**Comment by thiagolunardi** [comment]
Fechando chamado.
