### ISSUE TITLE
Qual classe deve invocar o Repositório ?

### ISSUE THREAD

**Issue by penihel** [thiagolunardi/MvcMusicStoreDDD#7]
Eu faço DDD acessando os repositórios sempre da camada de "Application". 
http://stackoverflow.com/questions/14256186/where-to-call-repository-update-in-ddd

Porém nos seus exemplos você sempre utiliza acessando pelo Domain Service.

Porque ? Não seria melhor pelo "Application Service"

**Comment by thiagolunardi** [comment]
Sim, você acessar o repositório da Application, desde que para somente consultas (dados desconectados, sem proxy). Pois essas camadas possuem responsabilidades diferentes.

Application trata diretamente de requisições vindas da sua apresentação (web, api, job), traduz informações de input para os tipos de entidade que sua solução possui (na camada de domínio) e faz as chamadas no domain service.

Domain Service é quem valida e realiza comportamentos no seu domínio disparado por modificações em suas entidades.

**Comment by penihel** [comment]
Sim.
Minha dúvida é porque neste livro da Microsoft Espanha
(http://blogs.msdn.com/b/cesardelatorre/archive/2010/03/26/our-brand-new-ddd-n-layer-net-4-0-architecture-guide-book-and-sample-app-in-codeplex.aspx) eles falam claramente que é "errado" chamar o repositório pelo "Domain Service", que o lugar correto é o "Application Service"

Eu faço assim conforme está no livro, e vi que no exemplo aqui é justamente o contrário. Minha dúvida era mais pra entender o porque a diferença.

Mas de qualquer forma obrigado pela atenção

**Comment by thiagolunardi** [comment]
Na própria página do livro mostra que existe a camada de Dominio entre a Application e a Repository.

Nesta imagem, retirada do livro do Eric Evans - "especificador" do DDD - ilustra isso também. Que vc pode acessar o repositório direto da AppService, desde de que somente leitura.

![ddd_png_pure](https://cloud.githubusercontent.com/assets/5428523/7596866/8b4dbd96-f8c6-11e4-86da-a5fdd2fbfbe7.png)

A Domain Service é quem é responsável por manipular os dados das entidades do seu domínio. Se vc pula a Domain Service, passa a ter um modelo de arquitetura anêmico, bolovo. A Domain 
Service ficaria sem responsabilidades.
