### ISSUE TITLE
TDD

### ISSUE THREAD

**Issue by wandelson** [thiagolunardi/MvcMusicStoreDDD#8]
Onde foi aplicado TDD ?

**Comment by thiagolunardi** [comment]
Não foi, ainda. A proposta desse projeto é de colaboração.
A próxima atualização vou publicar DDD rico - o atual é um DDD anêmico.
Se vc puder colaborar, e adicionar testes, faz commit que aprovo para irmos atendendo todos os patterns.
Me ajuda?

**Comment by wandelson** [comment]
Thiago, 


Ultimamente estou em projeto, assim que tiver um tempo livre faço alguns commits.
