### ISSUE TITLE
Uso do System.Web na camada de Infra

### ISSUE THREAD

**Issue by jedielson** [thiagolunardi/MvcMusicStoreDDD#9]
Thiago, uma dúvida.

No context da aplicação, há uma referencia ao System.Web, na classe ContextManager<TContext>.

Por que é necessário fazer uma referencia à System.Web nesta camada de aplicação?
Qual a necessidade e qual a função específica deste componente na aplicação.

Isto não força a aplicação a sempre depender de um HttpContext, e por consequencia, rodar somente na Web?

Obrigado pela força.

**Comment by thiagolunardi** [comment]
Sim, pior que força mesmo. Isso pq a ideia é manter apenas um Contexto por Requisição Web. Então a referencia ao Contexto de repositório fica "hospedado" no contexto web.

Estamos trabalhando em outra forma de garantir isso sem o uso do System.Web, nem do ServiceLocator.

Se tiver alguma sugestão, envia um pull request que se for leval, subimos.
